apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  NGINX_ENVSUBST_TEMPLATE_DIR: /etc/nginx/templates
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-env
  labels:
    app: nginx-env
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: nginx-config