apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: simple-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: simple-cronjob
          labels:
            app: simple-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: python-job
              image: paralun/python-job:v1       

    