apiVersion: v1
kind: Pod
metadata:
  name: nginx-env
  labels:
    app: nginx-env
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      env:
        - name: NGINX_ENVSUBST_TEMPLATE_DIR
          value: /etc/nginx/templates