apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector:
    app: nginx-lbl
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-lbl
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80