apiVersion: v1
kind: Secret
metadata:
  name: psql-secret
stringData:
  POSTGRES_USER: admin
  POSTGRES_DB: exampledb
---
apiVersion: v1
kind: Secret
metadata:
  name: psql-secret-base64
data:
  POSTGRES_PASSWORD: cmFoYXNpYQ==
---
apiVersion: v1
kind: Pod
metadata:
  name: psql-pod
  labels:
    app: psql
spec:
  containers:
    - name: psql
      image: postgres:alpine
      ports:
        - containerPort: 5432
      envFrom:
        - secretRef:
            name: psql-secret
        - secretRef:
            name: psql-secret-base64
