apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ngnix-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-lbl
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-lbl
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-lbl
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    name: nginx-ingress
spec:
  rules:
    - host: paralun.com
      http:
        paths:
          - path: /service1
            backend:
              serviceName: nginx-service
              servicePort: 80